# Generated by Django 4.2.7 on 2026-02-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusmart_project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
