# Generated by Django 4.2.7 on 2026-02-16 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('store_created', 'Store Created'), ('product_added', 'Product Added'), ('product_edited', 'Product Edited'), ('product_deleted', 'Product Deleted'), ('order_placed', 'Order Placed'), ('order_status_updated', 'Order Status Updated'), ('chat_message', 'Chat Message'), ('store_blocked', 'Store Blocked'), ('store_deactivated', 'Store Deactivated'), ('user_created', 'User Created'), ('user_role_changed', 'User Role Changed')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='logs_system_user_id_0e0614_idx'), models.Index(fields=['timestamp'], name='logs_system_timesta_1ce06b_idx')],
            },
        ),
    ]
