# Generated by Django 4.2.7 on 2026-02-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp phone number (with country code, e.g., +233XXXXXXXXX)', max_length=20, null=True),
        ),
    ]
