# Generated by Django 4.2.7 on 2026-02-19 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_store_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='entrepreneur',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
    ]
